$(function(){
	//导航栏
	$(".list-1").click(function(){
		if($(".duce>div:nth-child(1)").css("display")=="none"){
			$(".duce>div:nth-child(1)").slideDown(500);
			$(".duce>div:nth-child(1)").siblings().slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}else{
			$(".duce>div:nth-child(1)").slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}
	})
	$(".list-2").click(function(){
		if($(".duce>div:nth-child(2)").css("display")=="none"){
			$(".duce>div:nth-child(2)").slideDown(500)
			$(".duce>div:nth-child(2)").siblings().slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}else{
			$(".duce>div:nth-child(2)").slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}
	})
	$(".list-3").click(function(){
		if($(".duce>div:nth-child(3)").css("display")=="none"){
			$(".duce>div:nth-child(3)").slideDown(500)
			$(".duce>div:nth-child(3)").siblings().slideUp(500);
			if($(".stockholderTab").css("display")=="none"){
				clearInterval(time);
				var time=setTimeout(function(){
					$(".stockholderTab").slideDown()
				},500)
								
			}
		}else{
			$(".duce>div:nth-child(3)").slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}
	})
	
	$(".list-4").click(function(){
		if($(".duce>div:nth-child(4)").css("display")=="none"){
			$(".duce>div:nth-child(4)").slideDown(500)
			$(".duce>div:nth-child(4)").siblings().slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}else{
			$(".duce>div:nth-child(4)").slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}
	})
	$(".list-5").click(function(){
		if($(".duce>div:nth-child(5)").css("display")=="none"){
			$(".duce>div:nth-child(5)").slideDown(500)
			$(".duce>div:nth-child(5)").siblings().slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}else{
			$(".duce>div:nth-child(5)").slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}
	})
	$(".list-6").click(function(){
		if($(".duce>div:nth-child(6)").css("display")=="none"){
			$(".duce>div:nth-child(6)").slideDown(500)
			$(".duce>div:nth-child(6)").siblings().slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}else{
			$(".duce>div:nth-child(6)").slideUp(500);
			if($(".stockholderTab").css("display")=="block"){
				$(".stockholderTab").hide()
			}
		}
	})
})
